#!/bin/bash
# 🚀 ATS Resume Checker - Three Service Startup Guide

echo "🚀 ATS Resume Checker - Starting All Services"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ MongoDB:        Running (brew services)"
echo "⏳ Backend:        Opening in Terminal 1..."
echo "⏳ ML Service:     Opening in Terminal 2..."
echo "⏳ Frontend:       Opening in Terminal 3..."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To start services manually in separate terminals:"
echo ""
echo "Terminal 1 - Backend (Express):"
echo "  cd /Users/zuhairshah/Documents/Ats-checker/server"
echo "  npm run dev"
echo ""
echo "Terminal 2 - ML Service (FastAPI):"
echo "  cd /Users/zuhairshah/Documents/Ats-checker/ml-service"
echo "  source venv/bin/activate"
echo "  python main.py"
echo ""
echo "Terminal 3 - Frontend (React):"
echo "  cd /Users/zuhairshah/Documents/Ats-checker/client"
echo "  npm start"
echo ""
echo "Then visit: http://localhost:3000"
echo ""
echo "🎉 All services configured and ready!"
